export type PeticionPedidos = {
  pedidos: Pedido[];
  totalnumpedidos: number;
  totalNeto: string;
  totalFacturable: string;
  totalEfectivo: string;
  totalCobraReparto: string;
  totalYaPagado: string;
  totalOnline: string;
  mensaje: string;
};

export type Pedidos = Pedido[];

export type Pedido = {
  rechazopedido: any[];
  detalles: any[];
  codigopromocion: any;
  descuento: number;
  importedto: number;
  importedtoenvio: number;
  importedtook: number;
  importedtoenviook: number;
  envioobservaciones: any;
  importeproductos: number;
  importeenvio: number;
  comisionpago: number;
  preciototal: number;
  observaciones: any;
  formapago: string;
  formaentrega: string;
  enviodireccion: any;
  enviocodpostal: any;
  enviomunicipio: any;
  envioprovincia: any;
  fechahoraprograma: any;
  margenentregaprog: any;
  tiempoestimado: number;
  tiempoestimadoest?: number;
  horarespuestaest?: string;
  horaentregaestimada?: string;
  pagado: boolean;
  numeropedidoest: string;
  origen: string;
  cambio: any;
  webparticular: boolean;
  userdeestablec: any;
  horaasignarider: any;
  verider: any;
  quienreparte: any;
  lat: any;
  lon: any;
  repetido?: number;
  prioridad: any;
  tpotrayecto: any;
  tpoentrega: any;
  tpototal: any;
  pminenviofechaped: any;
  id: number;
  createdAt: string;
  updatedAt: string;
  usuario: number;
  establecimiento: Establecimiento;
  estado: Estado;
  factura: any;
  facturatransp: any;
  transferencia: any;
  invitacion: any;
  rider: any;
  pedidoajustado: any;
  updatedBy: number;
  entrada: string;
};

export type Establecimiento = {
  nombre: string;
  email: string;
  imagen: string;
  direccion: string;
  codpostal: string;
  municipio: string;
  provincia: string;
  loclatitud: number;
  loclongitud: number;
  abierto: boolean;
  pedidoonline: boolean;
  enviodomicilio: boolean;
  arecoger: boolean;
  pedidominimo: number;
  importeenvio: number;
  tiempoenvio: number;
  tiempopedido: number;
  codurl: any;
  codigo: string;
  asumecompago: boolean;
  acauto: boolean;
  reiniciarprodagotados: boolean;
  importeenvgratis: any;
  relevancia: number;
  distmax: number;
  versioncarta: number;
  pedmesa: any;
  imgcabecera: any;
  ped1pagoonline: any;
  fechabaja: any;
  horariofestdomingo: boolean;
  cerradohasta: any;
  tiesca: string;
  versioninfob: number;
  reparto: number;
  efectivorepartook: any;
  gestmensajesusu: boolean;
  sumartiempoenvio: any;
  tiempopedsinresp: number;
  llamadaauto: boolean;
  programapedidos: boolean;
  solopedidosprogenv: any;
  margenentregasprogenv: number;
  margenentregasprogrec: number;
  progantelacion: any;
  imglistado: any;
  emailavisopednormales: any;
  emailavisopedprogr: any;
  emailresumenpedprog: any;
  emailavisopedsinresponder: any;
  edcarta: any;
  siempreabierto: any;
  distpedidos: any;
  uuid: any;
  puedeAjustar: any;
  usaSemaforo: any;
  id: number;
  cliente: any;
  tipoestablecimiento: number;
  infoalergenoest: number;
  zona: any;
  sector: number;
};

export type Estado = {
  codigo: string;
  nombre: string;
  descripcion: string;
  imagen?: string;
  id: number;
};

export const PEDIDOS: Pedidos = [
  {
    rechazopedido: [],
    detalles: [],
    codigopromocion: null,
    descuento: 0,
    importedto: 0,
    importedtoenvio: 0,
    importedtook: 0,
    importedtoenviook: 0,
    envioobservaciones: null,
    importeproductos: 10,
    importeenvio: 0,
    comisionpago: 0,
    preciototal: 10,
    observaciones: null,
    formapago: 'EF',
    formaentrega: 'R',
    enviodireccion: null,
    enviocodpostal: null,
    enviomunicipio: null,
    envioprovincia: null,
    fechahoraprograma: null,
    margenentregaprog: null,
    tiempoestimado: 30,
    tiempoestimadoest: 15,
    horarespuestaest: '2024-07-18T16:27:36.000Z',
    horaentregaestimada: '2024-07-18T16:42:36.000Z',
    pagado: false,
    numeropedidoest: '288-11',
    origen: 'W',
    cambio: null,
    webparticular: false,
    userdeestablec: null,
    horaasignarider: null,
    verider: null,
    quienreparte: null,
    lat: null,
    lon: null,
    repetido: 0,
    prioridad: null,
    tpotrayecto: null,
    tpoentrega: null,
    tpototal: null,
    pminenviofechaped: null,
    id: 1758495,
    createdAt: '2024-07-18T16:26:34.000Z',
    updatedAt: '2024-07-18T18:14:18.000Z',
    usuario: 292,
    establecimiento: {
      nombre: 'Bar de Pruebas 2',
      email: 'barpruebas2@oidokocina.com',
      imagen: '288/bar-de-pruebas-2-comida-domicilio.png',
      direccion: 'Cl. Pruebas',
      codpostal: '60000',
      municipio: 'Localidad de Pruebas',
      provincia: 'Pruebas',
      loclatitud: 39.868,
      loclongitud: -104.972,
      abierto: true,
      pedidoonline: true,
      enviodomicilio: true,
      arecoger: true,
      pedidominimo: 10,
      importeenvio: 1.5,
      tiempoenvio: 25,
      tiempopedido: 15,
      codurl: null,
      codigo: 'bar-de-pruebas-2',
      asumecompago: false,
      acauto: true,
      reiniciarprodagotados: true,
      importeenvgratis: null,
      relevancia: 1,
      distmax: 10000,
      versioncarta: 85,
      pedmesa: null,
      imgcabecera: null,
      ped1pagoonline: null,
      fechabaja: null,
      horariofestdomingo: true,
      cerradohasta: null,
      tiesca: '25-35 minutos',
      versioninfob: 43400,
      reparto: 0,
      efectivorepartook: null,
      gestmensajesusu: true,
      sumartiempoenvio: null,
      tiempopedsinresp: 0,
      llamadaauto: false,
      programapedidos: true,
      solopedidosprogenv: null,
      margenentregasprogenv: 30,
      margenentregasprogrec: 15,
      progantelacion: null,
      imglistado: null,
      emailavisopednormales: null,
      emailavisopedprogr: null,
      emailresumenpedprog: null,
      emailavisopedsinresponder: null,
      edcarta: null,
      siempreabierto: null,
      distpedidos: null,
      uuid: null,
      puedeAjustar: null,
      usaSemaforo: null,
      id: 288,
      cliente: null,
      tipoestablecimiento: 1,
      infoalergenoest: 4,
      zona: null,
      sector: 1,
    },
    estado: {
      codigo: 'PR',
      nombre: 'Aceptado',
      descripcion: 'Pedido recibido y aceptado por el establecimiento',
      imagen: 'img/estado-aceptado.png',
      id: 2,
    },
    factura: null,
    facturatransp: null,
    transferencia: null,
    invitacion: null,
    rider: null,
    pedidoajustado: null,
    updatedBy: 40613,
    entrada: 'App',
  },
  {
    rechazopedido: [],
    detalles: [],
    codigopromocion: null,
    descuento: 0,
    importedto: 0,
    importedtoenvio: 0,
    importedtook: 0,
    importedtoenviook: 0,
    envioobservaciones: null,
    importeproductos: 6,
    importeenvio: 0,
    comisionpago: 0,
    preciototal: 6,
    observaciones: null,
    formapago: 'EF',
    formaentrega: 'R',
    enviodireccion: null,
    enviocodpostal: null,
    enviomunicipio: null,
    envioprovincia: null,
    fechahoraprograma: null,
    margenentregaprog: null,
    tiempoestimado: 30,

    pagado: false,
    numeropedidoest: '288-12',
    origen: 'W',
    cambio: null,
    webparticular: false,
    userdeestablec: null,
    horaasignarider: null,
    verider: null,
    quienreparte: null,
    lat: null,
    lon: null,

    prioridad: null,
    tpotrayecto: null,
    tpoentrega: null,
    tpototal: null,
    pminenviofechaped: null,
    id: 1774347,
    createdAt: '2024-07-29T07:21:24.000Z',
    updatedAt: '2024-07-29T07:21:24.000Z',
    usuario: 292,
    establecimiento: {
      nombre: 'Bar de Pruebas 2',
      email: 'barpruebas2@oidokocina.com',
      imagen: '288/bar-de-pruebas-2-comida-domicilio.png',
      direccion: 'Cl. Pruebas',
      codpostal: '60000',
      municipio: 'Localidad de Pruebas',
      provincia: 'Pruebas',
      loclatitud: 39.868,
      loclongitud: -104.972,
      abierto: true,
      pedidoonline: true,
      enviodomicilio: true,
      arecoger: true,
      pedidominimo: 10,
      importeenvio: 1.5,
      tiempoenvio: 25,
      tiempopedido: 15,
      codurl: null,
      codigo: 'bar-de-pruebas-2',
      asumecompago: false,
      acauto: true,
      reiniciarprodagotados: true,
      importeenvgratis: null,
      relevancia: 1,
      distmax: 10000,
      versioncarta: 85,
      pedmesa: null,
      imgcabecera: null,
      ped1pagoonline: null,
      fechabaja: null,
      horariofestdomingo: true,
      cerradohasta: null,
      tiesca: '25-35 minutos',
      versioninfob: 43400,
      reparto: 0,
      efectivorepartook: null,
      gestmensajesusu: true,
      sumartiempoenvio: null,
      tiempopedsinresp: 0,
      llamadaauto: false,
      programapedidos: true,
      solopedidosprogenv: null,
      margenentregasprogenv: 30,
      margenentregasprogrec: 15,
      progantelacion: null,
      imglistado: null,
      emailavisopednormales: null,
      emailavisopedprogr: null,
      emailresumenpedprog: null,
      emailavisopedsinresponder: null,
      edcarta: null,
      siempreabierto: null,
      distpedidos: null,
      uuid: null,
      puedeAjustar: null,
      usaSemaforo: null,
      id: 288,
      cliente: null,
      tipoestablecimiento: 1,
      infoalergenoest: 4,
      zona: null,
      sector: 1,
    },
    estado: {
      codigo: 'NU',
      nombre: 'Nuevo',
      descripcion: 'Pedido nuevo no contestado por el establecimiento',
      id: 1,
    },
    factura: null,
    facturatransp: null,
    transferencia: null,
    invitacion: null,
    rider: null,
    pedidoajustado: null,
    updatedBy: 292,
    entrada: 'App',
  },
];
